React u ikit component
GennadiyBakulin/adminpanel-on-react pull request #2
Opened 2022-10-26 16:09 UTC by GennadiyBakulin

Добрый вечер Джабраил!
Прошу проверить мою работу по ДЗ:
2. Собрать шапку страницы на mocks

2022-11-01 01:52 UTC, Muslik requested changes
Будет видео

2022-11-05 14:32 UTC, Muslik commented on .eslintrc.json
> +      "tab",
Отступ всегда пробелы

2022-11-05 14:33 UTC, Muslik commented on .eslintrc.json
> -{
Я не вижу файла gitignore с игнорируемыми там node_modules!

2022-11-05 14:34 UTC, Muslik commented on src/contexts/ThemeContext.js
> +	night: 'night',
Отступ два пробела. Просьба исправить.

2022-11-05 14:34 UTC, Muslik commented on src/providers/ThemeProvider.js
> +	document.documentElement.dataset.theme = theme;
Это должно быть обернуто в useEffect

2022-11-05 14:44 UTC, Muslik requested changes

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Button/Button.jsx
> +			{value}
value тут быть не должно.

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Button/Button.jsx
> +			{value}
Текст приходит только через children

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Button/Button.jsx
> +		<button className={blockClass} onClick={props.onClick} type='button'>
type может быть не только button. Хотелось бы чтобы я мог его менять через пропсы

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +	disabled: 'disabled',
disabled должен приходить в сам input:
```javascript
<Input disabled />
```

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +	multiple: 'multiple'
multiple никак не относится к инпуту. Вы пытаетесь подстроить инпут под свой дропдаун. Не надо так

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +export const Input = ({ className, inputStates, title, placeholder, value = '', onChange, prevText }) => {
prevText звучит как предыдущее значение.
prefixText будет намного лучше

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +	incorrect: 'incorrect',
Здесь останется только incorrect и его можно передать напрямую сразу через props-ы

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Searchbar/Searchbar.jsx
> +			{filled && <Button className={styles.button} size='small' icon='x_medium' {...props} />}
У вас есть value. Для того чтобы понять что инпут заполнен не нужно передавать отдельный props

2022-11-05 14:44 UTC, Muslik commented on src/shared/components/Searchbar/Searchbar.jsx
> +			{filled && <Button className={styles.button} size='small' icon='x_medium' {...props} />}
Почему вы пропсы пропихиваете в кнопку. Они не имеют к ней отношения

2022-11-05 14:44 UTC, Muslik commented on src/AdminPage/AdminPage.jsx
> +	return (
По умолчанию - светлая тема. Ваш ui не должен так жестко обрезаться по центру Хочу чтобы он тянулся на ширину. Ни один из ваших инпутов не работает. Дропдаун со статусами не работает

2022-11-05 14:44 UTC, Muslik commented on src/modules/Search/Search.jsx
> +	const [showFilters, setShowFilters] = useState(false);
Почему у вас в компоненте Search откуда то взялись фильтры )

2022-11-05 15:03 UTC, GennadiyBakulin commented on .eslintrc.json
> +      "tab",
исправил

2022-11-05 15:03 UTC, GennadiyBakulin commented on .eslintrc.json
> -{
добавил gitignore  в проект

2022-11-05 15:03 UTC, GennadiyBakulin commented on src/contexts/ThemeContext.js
> +	night: 'night',
исправил

2022-11-05 15:16 UTC, GennadiyBakulin commented on src/shared/components/Button/Button.jsx
> +			{value}
исправил

2022-11-05 15:21 UTC, GennadiyBakulin commented on src/shared/components/Input/Input.jsx
> +export const Input = ({ className, inputStates, title, placeholder, value = '', onChange, prevText }) => {
изменил

2022-11-05 15:23 UTC, GennadiyBakulin commented on src/shared/components/Searchbar/Searchbar.jsx
> +			{filled && <Button className={styles.button} size='small' icon='x_medium' {...props} />}
исправил

2022-11-05 15:26 UTC, GennadiyBakulin commented on src/AdminPage/AdminPage.jsx
> +	return (
исправил

2022-11-05 15:29 UTC, GennadiyBakulin commented on src/modules/Search/Search.jsx
> +	const [showFilters, setShowFilters] = useState(false);
Это выпадающий блок с фильтрами, а Search это основной блок как если бы без использования фильтров.

2022-11-05 15:44 UTC, GennadiyBakulin commented on src/shared/components/Button/Button.jsx
> +		<button className={blockClass} onClick={props.onClick} type='button'>
исправил

2022-11-05 15:47 UTC, GennadiyBakulin commented on src/modules/Search/Search.jsx
> +	const [showFilters, setShowFilters] = useState(false);
Search это модуль

2022-11-06 05:31 UTC, GennadiyBakulin commented on src/providers/ThemeProvider.js
> +	document.documentElement.dataset.theme = theme;
исправил

2022-11-06 05:41 UTC, GennadiyBakulin commented on src/shared/components/Input/Input.jsx
> +	disabled: 'disabled',
исправил

2022-11-06 06:48 UTC, GennadiyBakulin commented on src/shared/components/Input/Input.jsx
> +	incorrect: 'incorrect',
исправил

2022-11-06 06:55 UTC, GennadiyBakulin commented on src/shared/components/Input/Input.jsx
> +	multiple: 'multiple'
исправил

2022-11-06 12:17 UTC, GennadiyBakulin commented on src/modules/Search/Search.jsx
> +	const [showFilters, setShowFilters] = useState(false);
исправил

2022-11-06 12:18 UTC, GennadiyBakulin commented
Добрый вечер Джабраил!
Замечания по Ревью исправил.

2022-11-06 22:59 UTC, Muslik approved these changes
Исправьте несколько замечаний

2022-11-06 22:59 UTC, Muslik commented on src/shared/components/Button/Button.module.css
> +  opacity: 0.6;
Уберите пожалуйста opacity )
Кнопка становится очень блеклой при наведении

2022-11-06 22:59 UTC, Muslik commented on src/providers/ThemeProvider.js
> +  });
Массив dependencies забыли, [theme]

2022-11-06 22:59 UTC, Muslik commented on src/shared/components/Button/Button.jsx
> +export const Button = ({ className, theme, size, children, icon, typeButton = 'button', ...props }) => {
typeButton просто type. Зачем его вообще переименовывать

2022-11-06 22:59 UTC, Muslik commented on src/modules/Filter/FilterSelectorsPanel/FilterOrderStatus/FilterOrderStatus.jsx
> +      ? 'статус не выбран'
По Макету должно быть Любой. Стрелочка в дропдауне повернута не в ту сторону

2022-11-06 22:59 UTC, Muslik commented on src/modules/Filter/FilterSelectorsPanel/FilterOrderStatus/FilterOrderStatus.jsx
> +    checkedOnlyStatuses.length === 0
Если выбраны все статусы, тоже должно отображаться "Любой"

2022-11-07 14:34 UTC, GennadiyBakulin commented on src/shared/components/Button/Button.module.css
> +  opacity: 0.6;
исправил

2022-11-07 14:36 UTC, GennadiyBakulin commented on src/providers/ThemeProvider.js
> +  });
исправил

2022-11-07 14:36 UTC, GennadiyBakulin commented on src/shared/components/Button/Button.jsx
> +export const Button = ({ className, theme, size, children, icon, typeButton = 'button', ...props }) => {
исправил

2022-11-07 14:37 UTC, GennadiyBakulin commented on src/modules/Filter/FilterSelectorsPanel/FilterOrderStatus/FilterOrderStatus.jsx
> +    checkedOnlyStatuses.length === 0
исправил

2022-11-07 14:46 UTC, GennadiyBakulin commented on src/modules/Filter/FilterSelectorsPanel/FilterOrderStatus/FilterOrderStatus.jsx
> +      ? 'статус не выбран'
исправил

2022-11-07 17:28 UTC, closed without merging

2022-11-07 17:29 UTC, GennadiyBakulin commented
approved