React table
GennadiyBakulin/adminpanel-on-react pull request #3
Opened 2022-11-11 15:19 UTC by GennadiyBakulin

Добрый вечер Джабраил!
Прошу проверить ДЗ 3.

2022-11-11 18:54 UTC, Muslik commented
Таблица не на всю высоту

2022-11-11 18:55 UTC, Muslik requested changes
По ДЗ - таблица должна быть общим компонентом.
Гляньте работы студентов:
denisov-ie, Hellomyguest, Balaberd.

2022-11-12 13:58 UTC, GennadiyBakulin commented
Замечания исправил - (Таблица не на всю высоту, По ДЗ - таблица должна быть общим компонентом)

2022-11-13 00:05 UTC, Muslik requested changes

2022-11-13 00:05 UTC, Muslik commented on src/shared/components/Table/TableCell/TableCell.jsx
> +export const TableCell = ({ className, name, children }) => {
Зачем тут name. И почему в дальнейшем это превращается в id?

2022-11-13 00:05 UTC, Muslik commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +export const TableHeaderCell = ({ className, name, click, children, onClick }) => {
Нет никакого смысла передавать насильно name просто чтобы достать его из event-а.
И это не name, а id.

При вызове вы делаете так:
```javascript
<TableHeaderCell onClick={handleClickCell('date')} />
```
а сам handler будет выглядеть так:
```javascript
const handleClickCell = (key) => () => {...}
```

И не нужно ничего прокидывать

2022-11-13 00:05 UTC, Muslik commented on src/modules/OrderTable/OrderTableHeader/OrderTableHeader.jsx
> +        <Icon
Вы сделал header для таблички. И header предполагает в себе возможное наличие сортировки.

Так почему бы не пихнуть сортировку туда.

```javascript
<TableHeaderCell isActive={sortField === 'date'} onSort={handleClickSort('date')} direction="desc" />
```

И в самом TableHeaderCell в случае наличия onSort будет отображаться иконка и соответственно hover.
В случае isActive будет выделять активным цветом ячейка.
И стрелочка будет всегда отображаться и поворачиваться в зависимости от direction.

В этом и заключается смысл компонента TableHeaderCell

Сейчас у вас некоторые поля выделяются hover-ом хотя при нажатии на них ничего не происходит. Так быть не должно

2022-11-13 00:05 UTC, Muslik commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +export const TableHeaderCell = ({ className, name, click, children, onClick }) => {
Сам props click странно выглядит. Непонятно что он вообще может значить

2022-11-13 00:05 UTC, Muslik commented on src/modules/OrderTable/OrderTableHeader/OrderTableHeader.module.css
> +._ .checkboxCell:hover,
Это явно не тут должно быть. А в самом общем компоненте

2022-11-13 00:05 UTC, Muslik commented on src/shared/components/Table/TableRow/TableRow.jsx
> +    <div className={blockClass} id={id}>
Зачем тут id

2022-11-13 00:05 UTC, Muslik commented on src/modules/OrderTable/OrderTableBody/OrderTableBody.jsx
> +let srt = ordersMock.concat();
И как по названию переменной понять что она содержит? )

2022-11-13 04:41 UTC, GennadiyBakulin commented on src/shared/components/Table/TableCell/TableCell.jsx
> +export const TableCell = ({ className, name, children }) => {
Исправил

2022-11-13 04:51 UTC, GennadiyBakulin commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +export const TableHeaderCell = ({ className, name, click, children, onClick }) => {
Исправил

2022-11-13 04:53 UTC, GennadiyBakulin commented on src/shared/components/Table/TableRow/TableRow.jsx
> +    <div className={blockClass} id={id}>
Исправил

2022-11-13 04:56 UTC, GennadiyBakulin commented on src/modules/OrderTable/OrderTableBody/OrderTableBody.jsx
> +let srt = ordersMock.concat();
Исправил

2022-11-13 05:28 UTC, GennadiyBakulin commented on src/modules/OrderTable/OrderTableHeader/OrderTableHeader.module.css
> +._ .checkboxCell:hover,
Исправил

2022-11-13 06:22 UTC, GennadiyBakulin commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +export const TableHeaderCell = ({ className, name, click, children, onClick }) => {
Исправил

2022-11-13 06:22 UTC, GennadiyBakulin commented on src/modules/OrderTable/OrderTableHeader/OrderTableHeader.jsx
> +        <Icon
Исправил

2022-11-13 06:24 UTC, GennadiyBakulin commented
Замечания исправил

2022-11-13 12:46 UTC, Muslik commented
cursor: pointer на некликабельных ячейках шапки убрать

2022-11-13 12:50 UTC, Muslik approved these changes
Мелкие замечания

2022-11-13 12:50 UTC, Muslik commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +    [styles.direction]: direction === true
direction переводится как направление.
true/false - да/нет - ок/не ок
direction = true -> направление ок? 
Звучит странно. Поэтому туда идет либо числовое значение либо буквенное:
и оно может быть asc/desc или 1/-1

2022-11-13 12:50 UTC, Muslik commented on src/shared/components/Table/TableRow/TableRow.module.css
> +/*._:hover {*/
убрать

2022-11-13 12:50 UTC, Muslik commented on src/shared/components/Table/TableCell/TableCell.jsx
> +export const TableCell = ({ className, id, children }) => {
id тут не нужен

2022-11-13 14:32 UTC, GennadiyBakulin commented
Исправил мелкие недочеты

2022-11-13 14:32 UTC, closed without merging